### ISSUE TITLE
[✅]Demo 工程跑不起来啊

### ISSUE THREAD

**Issue by kaaaaai** [iFLYOS-OPEN/SDK-EVS-iOS#1]
![image](https://user-images.githubusercontent.com/30493584/82749673-69685580-9ddd-11ea-8560-80f41b360c0f.png)
我把 podfile 文件注释了一大段才 pod install 成功。但是运行时仍会提醒找不到头文件
![image](https://user-images.githubusercontent.com/30493584/82749704-a2082f00-9ddd-11ea-8791-70f829e72c8e.png)

**Comment by packyzhou** [comment]
请重新在setting -> header search Paths设置头文件路径

**Comment by kaaaaai** [comment]
嗯，可以了，我在全局搜了一下这个 EvsSDKForiOs.h 文件，把他和他所在的所有文件都拖入工程，问题就解决了。
